### ISSUE TITLE
how to use boostrap instead of semantic

### ISSUE THREAD

**Issue by buziyborni** [Mrigank11/embetacloud#1]
this is a nice project thanks for that, but please why not use boostrap instead of semantic since most people are not familiar with semantic especially me i will need help with boostrap

**Comment by Mrigank11** [comment]
Glad to see your interest in the project,
Semantic-ui is new and better UI framework than Bootstrap, the main point why I used Semantic-UI is very understandable coding, please try to read it, it is very semantic :) like for a grid system in bootstrap we'll write `class="column-sm"` etc. we need to refer documentation if we forget something but its not the case with Semantic-UI, we'll just write `class="ui four wide column"` which is very much understandable.

**Comment by buziyborni** [comment]
thanks for making it clear, i will try and read on their documentation and give it a try
