### ISSUE TITLE
mega support!

### ISSUE THREAD

**Issue by shashi007** [Mrigank11/embetacloud#13]
Would be nice to have an option to upload on mega.co.nz

**Comment by Mrigank11** [comment]
Sure, I will add that soon. 
Thank you for your suggestion !

**Comment by shashi007** [comment]
Nice! Thanks.

**Comment by Mrigank11** [comment]
Sorry, but due to unavailability of official api for javascript from mega.co.nz , it won't happen soon. There is an unofficial one but it doesn't look promising.
If you have an idea to implement the API in javascript, it would be helpful !

**Comment by shashi007** [comment]
I couldn't find anything except this https://github.com/prashanthca/beam/blob/master/index.js
If you think you can make it work great! Otherwise you keep working on other things lol.

**Comment by Mrigank11** [comment]
Now single files can be uploaded to mega.

**Comment by shashi007** [comment]
Cool! :-)
