### ISSUE TITLE
If possible please add these cloud storage!!

### ISSUE THREAD

**Issue by hackevil** [Mrigank11/embetacloud#16]
1. Filescdn(Need It Urgently)
2. Mega.nz
3. Oboom
4. 1Fichier(Need It Urgently)
5. Dropbox
6. Usercloud
7. Userfiles

If possible please add them

**Comment by Mrigank11** [comment]
1. Filescdn : no API provided
2. Mega.nz : no API for javascript
3. Oboom : possible
4. 1Fichier(Need It Urgently) : no API provided
5. Dropbox : 👍 will be done easily
6. Usercloud : no api provided
7. Userfiles : no API provided

**Comment by FrozenFighter** [comment]
@Mrigank11 
You should add support for Onedrive because it give 1TB free for all Microsoft Office 365 subscriber.
I think nearly everyone has it.

Sorry, for my bad English.

**Comment by pmwoodward3** [comment]
Could we also add Amazon Cloud Drive? It works really well with Rclone and a few other tools, would probably be easy to get working with this, right?

**Comment by Mrigank11** [comment]
#30
