### ISSUE TITLE
I cannot understand how to generate the api from google

### ISSUE THREAD

**Issue by hackevil** [Mrigank11/embetacloud#17]
hi please will u explain me how can i generate the api i have tried many but none of them work to generate the api,will u please make video how to generate these api an how to implement these on heroku please i need it urgently

**Comment by Mrigank11** [comment]
1. Head on to [Google Developer Console](https://console.developers.google.com) and create a project.
2. Click on Credentials
3. Create new credentials, note down CLIENT_ID and CLIENT_SECRET
4. In "Authorised redirect URIs" section, add "https://&lt;your heroku app url like a.herokuapp.com&gt;/oauthCallback"
5. Again open [Google Developer Console](https://console.developers.google.com), click on "Enable API" and enable Google Drive API
6. Click on "Deploy to Heroku" button in Readme.md and fill the CLIENT_ID and CLIENT_SECRET you noted above, in the GOOGLE_REDIRECT_URL write down the url you entered in step 4
7. Done!
Tell me in which step you're stuck.

**Comment by Mrigank11** [comment]
@hackevil did you made it?
