### ISSUE TITLE
Help needed to deploy to DO 

### ISSUE THREAD

**Issue by CodeInSun** [Mrigank11/embetacloud#18]
How do i deploy this app to Digital Ocean ? 

Also can i run this locally. I tried `npm install` and `npm start` it returned these errors

```
upload-to-gdrive@1.0.0 start: `node server/server.js`
Exit status 1
Failed at the upload-to-gdrive@1.0.0 start script 'node server/server.js' 
```

**Comment by Mrigank11** [comment]
please try to run: `node server/server.js`
I (and others) are not having any problem like this, either provide more information or I can provide you remote support if you like because I am not able to reproduce it.

**Comment by CodeInSun** [comment]
I tried that command it returned this error 

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'pipe-io
```

**Comment by Mrigank11** [comment]
Looks like `npm install` didn't completed successfully, please try to do it again, from the beginning.

**Comment by CodeInSun** [comment]
Which version of npm are you using ?

**Comment by Mrigank11** [comment]
node v6.9.1 and npm v3.10.8

**Comment by CodeInSun** [comment]
@Mrigank11 How do i run this project on DO using docker ? Please share me the command for this.

**Comment by Mrigank11** [comment]
I've created a repo on dockerhub for this, to pull it, run: `docker pull mrigank11/embetacloud`
Then you can run it using `docker run <image name>`
To list images `docker images`

**Comment by CodeInSun** [comment]
It's not starting. Is there any direct command like this one from another project 

> $ docker run -d -p 3000:3000 -v /path/to/my/downloads:/downloads jpillora/cloud-torrent

**Comment by Mrigank11** [comment]
Sorry, I didn't provided the complete command : 
`docker run -d -p 3000:3000 -e GOOGLE_CLIENT_ID='***' -e GOOGLE_CLIENT_SECRET='***' -e GOOGLE_REDIRECT_URL='***' mrigank11/embetacloud node server/server.js`
Fill `***` with appropriate values.
If you want to debug, add `-e DEBUG='eMCloud:*'` and remove the `-d`

**Comment by CodeInSun** [comment]
Thanks for the help.
