### ISSUE TITLE
How to install this app through docker?

### ISSUE THREAD

**Issue by mikan01** [Mrigank11/embetacloud#19]
Please guide how to install and run this app through docker on Ubuntu. Thanks.

**Comment by Mrigank11** [comment]
`docker pull mrigank11/embetacloud`

**Comment by mikan01** [comment]
Hi,

After fetching the image using docker pull command, I tried to run it through docker run image command but for some reasons the app is not starting. I tried to access the app through browser @ localhost:3000 but it doesn't seems to be up. 

![docker](https://cloud.githubusercontent.com/assets/22120742/23132398/7566e29e-f7b3-11e6-9a70-1b351d397502.png)

Can you show me proper steps to do it. I am using Ubuntu VPS. Many thanks :)

**Comment by CodeInSun** [comment]
@mikan01 Same problem here. I also checked open ports using 

>netstat -ntpl 

It didn't show port 3000.

**Comment by Mrigank11** [comment]
Sorry, I didn't provided the complete command : 
`docker run -d -p 3000:3000 -e GOOGLE_CLIENT_ID='***' -e GOOGLE_CLIENT_SECRET='***' -e GOOGLE_REDIRECT_URL='***' mrigank11/embetacloud node server/server.js`
Fill `***` with appropriate values.
If you want to debug, add `-e DEBUG='eMCloud:*'` and remove the `-d`

**Comment by mikan01** [comment]
Thanks for your help. It's working fine now :D
