### ISSUE TITLE
Where to add these in the code.

### ISSUE THREAD

**Issue by hackevil** [Mrigank11/embetacloud#23]
Hey just wanna ask that how and where to add the credential in the code.
GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET
GOOGLE_REDIRECT_URL

**Comment by Mrigank11** [comment]
add them here  [here](https://github.com/Mrigank11/embetacloud/blob/master/server/Storages/GDrive/GDrive.ts#L8) and compile typescript or directly edit [js](https://github.com/Mrigank11/embetacloud/blob/master/server/Storages/GDrive/GDrive.js#L13).

like `CLIENT_ID = "<client id>";`
