### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by hackevil** [Mrigank11/embetacloud#24]
Hey buddy thanks to you for adding Mega.
Can it be hosted to openshift.
And how to deploy it to arukas.io
if not please suggest me good alternative to heroku.

**Comment by Mrigank11** [comment]
A new options have been added in main toolbar for switching clouds : 
![embeta cloud](https://cloud.githubusercontent.com/assets/16872657/24790838/7faa52b2-1b95-11e7-8246-f729f5065b9b.png)

Until you do not use Google Drive upload you don't need to set the creds. In that case I would recommend to disable Google Drive : 

Just comment from [here](https://github.com/Mrigank11/embetacloud/blob/master/server/Storages/Storages.ts#L6) to [here](https://github.com/Mrigank11/embetacloud/blob/master/server/Storages/Storages.ts#L9) or the corresponding section in [Storages.js](https://github.com/Mrigank11/embetacloud/blob/master/server/Storages/Storages.js) (if you don't want to compile Typescript)

**Comment by hackevil** [comment]
@Mrigank11 thanks buddy for your help one last question is that is there any alternative to heroku i foun Xervo.io recently but now they are shutting down their services from 28th ofaprilso i want to migrate somewhere else so please suggest me an alternative to heroku.

**Comment by Mrigank11** [comment]
give Arukas a [try](https://github.com/Mrigank11/embetacloud/issues/20#issuecomment-286735644)

**Comment by hackevil** [comment]
@Mrigank11 thx thx buddy you made my day.

**Comment by hackevil** [comment]
what does "Stream downloads to user" means??
does it streams media files

**Comment by hackevil** [comment]
How can i limit no of downloads an uploads of torrents.

**Comment by Mrigank11** [comment]
> And i have an idea also that is,can it be used to fetch web links of files from around the web and upload it to the cloud storage.

that's the reason why this project started, it was the first feature, please read first para of [README.md](https://github.com/Mrigank11/embetacloud/blob/master/README.md)

> And is there any possibilities of adding filecorn.com as cloud storage to eMbeta(Why did you named it eMbeta)

It's still in beta, why not wait. However, you can add it on your own, [adding new clouds](https://github.com/Mrigank11/embetacloud/blob/master/README.md#how-to-add-cloud-storage) is easy.


> what does "Stream downloads to user" means??
> does it streams media files

Well, I know it's not the best label, I couldn't think of anything better. Anyway, enabling it "streams downloads to user", means whenever a file is captured while you're browsing using the proxy, you'll get the "Download prompt". On the other hand, disabling it closes the window once a downloadable file is captured, making it less annoying.

> How can i limit no of downloads an uploads of torrents.

No such thing is included yet, you can add a condition [here](https://github.com/Mrigank11/embetacloud/blob/master/server/server.ts#L466) like `if(Object.keys(torrents).length > N) return;`

**Comment by hackevil** [comment]
Thanks it was very helpful.

**Comment by hackevil** [comment]
Hey i just found some bugs when the scrip is deployed on the arukas, i dont know what it is but i am not able to download the torrents or sign in to the clouds accounts.
![capture](https://cloud.githubusercontent.com/assets/23115256/24855306/ce2da040-1dfe-11e7-9b89-6b677fdf2ee7.PNG)

and what does the red sign on the upper right corner means.

**Comment by Mrigank11** [comment]
Well, sorry but I'm not able to reproduce this, it's working perfectly in my case. The screenshot suggests that websocket connection is unstable(the red sign).

Please tell me the steps to reproduce it.

**Comment by hackevil** [comment]
@Mrigank11 Here is a video, tell me if i am doing wrong anywhere.
https://vid.me/4zsr

**Comment by Mrigank11** [comment]
@hackevil  Create single instance.

**Comment by hackevil** [comment]
@Mrigank11 thanks buddy u are genius.

**Comment by ipainirfan** [comment]
Greetings. I got a problem when try to deploy using Arukas. For the port section it says there is no running container.
