### ISSUE TITLE
GOOGLE DRIVE Problem

### ISSUE THREAD

**Issue by praburamWAPKA** [Mrigank11/embetacloud#27]
GOOGLE_REDIRECT_URL (it should be <server address>/oauthCallback by default)

i just set http://domain.com/oauthCallback  as Redirect URL But Comes to end like  http://domain.com/oauthCallback?code=4/iI1ZoRlD5fxdp_xBDCnUi1vtBcx2Qq7dcjEIK3Orggg#

shows "Error"

**Comment by Mrigank11** [comment]
There is a problem getting tokens from Google, please set environment variable `DEBUG=eMCloud:*` for detailed error.

**Comment by Mrigank11** [comment]
Closing as no response received after a month.
Feel free to reopen.
