### ISSUE TITLE
heroku deploy issue 

### ISSUE THREAD

**Issue by nk932714** [Mrigank11/embetacloud#28]
heroku is suspending this app after deploy.

**Comment by Mrigank11** [comment]
This is expected as it's clearly mentioned in their TOS that p2p is not allowed.

I'll remove the "Deploy to heroku" button.

You need to find alternate nodejs/docker hosting platforms that allow p2p.

**Comment by nk932714** [comment]
thanks @Mrigank11  for your quick reply. Can you suggest me any alternative free hosting site except Openshift.

**Comment by Zecx** [comment]
i didn't see they talking about not allowing torrent in here

https://www.heroku.com/policy/salesforce-heroku-msa

**Comment by Mrigank11** [comment]
https://www.heroku.com/policy/aup

Read point 16.

**Comment by Zecx** [comment]
`Use the Service in connection with peer-to-peer file sharing`

i see, thanks

but some app torrent like this still work normally on heroku ?
like [this](https://github.com/karl-chan/google-drive-torrent)

how about that ?

**Comment by nk932714** [comment]
Some Of the old embeta cloud  repositories are also working on heroku. They are blocking new. Also heroku have detected they are affected by this repository most so they blocked this pirticular application. Also peerflix & jpillora repository is blocked. Because these are popular & affects heroku free service at high level. If you are paying for heroku services then they will not block any repository.
