### ISSUE TITLE
openshift deploy issue

### ISSUE THREAD

**Issue by nk932714** [Mrigank11/embetacloud#29]
Can you please check this repo deployment on Openshift. I am unable to deploy this on Openshift.  

it is displaying error 

**The container embetacloud is crashing frequently**

**Comment by nk932714** [comment]
@Mrigank11  FYI Pleae check[ this link ](https://github.com/bharadwajpro/node-torrent-cloud/commit/afe7befc330e7c892a01e8b61b7656c67a5580c9)

**Comment by Mrigank11** [comment]
Sorry @nk932714 for late reply.
But till now I'm not able to deploy on Openshift.
You can try using branch "ot" in my repo in which I've fixed the port problem. 
In my case it always says, "build failed" but everything seems good in the logs.

I'd recommend you to use AWS or try using the docker image: `mrigank11/embetacloud:ot`

**Comment by nk932714** [comment]
Error Log with docker image procedure 


  **| --> Scaled older deployment embetacloud-2 down
-- | --
  | --> Scaling embetacloud-3 to 1
  | --> Waiting up to 10m0s for pods in rc embetacloud-3 to become ready
  | W1009 06:14:42.446257       1 reflector.go:323] github.com/openshift/origin/pkg/deploy/strategy/support/lifecycle.go:509: watch of *api.Pod ended with: too old resource version: 75351387 (75358525)
  | error: update acceptor rejected embetacloud-3: pods for rc "embetacloud-3" took longer than 600 seconds to become ready**

**Comment by nk932714** [comment]
i don't know how its deployed but it is working on openshift now. But there is a issue of loading magnet

**Comment by Mrigank11** [comment]
I can't reproduce the issue(not even deploy on openshift). However, this error simply means connection to tracker timed-out. Either Openshift is blocking torrents or the torrent you choose is dead, try another.

**Comment by nk932714** [comment]
I deployed it using docker image pull. But i don't how. Initially it was giving me error while I was trying to deploy. I have tried two three hours then i gave up. But next day when I opened openshift it was deployed. Is there any way to check how i deployed.
I will try again andif  i get success then definitely i will tell you the procedure how i deployed.

**Comment by Guilty-King** [comment]
I tried deploying this on openshift and no problems so far
It's only been a day since deployment so will keep check 
I used mrigank11/embetacloud:ot Docker image
Thanks for your project , also let me know if you want to test anything

**Comment by Guilty-King** [comment]
I deployed it to openshift from docker image you mentioned above version ot and I can visit the app ,  sign in with Google account but can't load any magnets , also tried in-build search but same error loading magnets 
Let me know which logs to provide if it helps

**Comment by Mrigank11** [comment]
Confirmed. Openshift blocks torrent.

So, it's not gonna work on openshift.

**Comment by ParveenBhadooOfficial** [comment]
Same issue with AWS Deploy but only via links or inbuild search. Magnet links from thepirateway works fine.
