### ISSUE TITLE
Issue with loading magnets

### ISSUE THREAD

**Issue by nk932714** [Mrigank11/embetacloud#31]
**trying on codeanywhere.com**

Unable to load magnets

Can you please test your repo on Codeanywhere.com
**steps to reproduce the problem**
1) Login to codeanywhere
2) add new project 
3) click on github and select embetacloud
4) untick automatic select stack
5) select node.js & click ok
6) Now on SSH terminal clcik on NPM install
7) npm start
8) Goto your http://<URL>:8080 ( if you dont know your url then right click on your project and click on info)
![image](https://user-images.githubusercontent.com/29853208/32261891-6913e76a-bef7-11e7-906c-2ff6cb04d822.png)

9) search any torrent and try to download

i was also unable to load magnets on OpenShift

**Comment by Mrigank11** [comment]
codeanywhere.com does not allow torrents.

**Comment by nk932714** [comment]
@Mrigank11  it allows some torrents
e.g= http://releases.ubuntu.com/17.10/ubuntu-17.10-desktop-amd64.iso.torrent 
etc
Also the torrents from Rarbg works there.

But my main problem is why it is unable to load magnet file( same problem on Openshift ). 
Is there any other free alternative where i can deploy ( heroku is suspending app because of their t&c)

**Comment by nk932714** [comment]
Hi @Mrigank11 One more question 
is there any way to add Google account credentials with command line? 
thanks :)

**Comment by Mrigank11** [comment]
Just set the required envs: `export ENV_NAME=VALUE`

**Comment by nk932714** [comment]
thanks @Mrigank11
