### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by fuadhammam** [Mrigank11/embetacloud#37]
how can i solve this error message ? i'am install this on my vps 

![screenshot_197](https://user-images.githubusercontent.com/22473125/36718901-ff46848c-1bd5-11e8-937c-e964f79c08aa.png)

**Comment by Mrigank11** [comment]
`node` binary does not exist on your system. You've node but binary is named as `nodejs` not `node`. Also your node version is very old.

To resolve this, simply install `node`(This project is tested with `6.11.1`). 

I'd recommend using [n](https://github.com/tj/n) to easily install node. To use `n`, run 
```
curl -L https://git.io/n-install | bash
```
Then install node 6.11.1 by running:
```
n 6.11.1
```

**Comment by fuadhammam** [comment]
wait, i'll try it

**Comment by fuadhammam** [comment]
how about this ?

![screenshot_198](https://user-images.githubusercontent.com/22473125/36722029-14326b14-1bdf-11e8-8d5a-883373828ee8.png)

**Comment by Mrigank11** [comment]
I guess you did run `npm install`, did you?

**Comment by fuadhammam** [comment]
yeah i did `npm install` and this is what can i get

![screenshot_199](https://user-images.githubusercontent.com/22473125/36723610-5b01fd3a-1be3-11e8-8de2-f430c106c25e.png)

**Comment by Mrigank11** [comment]
I don't see any error in your screenshot. 
Did you let it complete? If yes, try to remove `node_modules` folder and run `npm install` again. 
After successful `npm install` it should work.

**Comment by fuadhammam** [comment]
not sure, but this is my step while i installing them

> clone to vps
> run this command `npm install`
> edit `..../server/storage/GDrive/GDrive.js` 
 . replace GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET / GOOGLE_REDIRECT_URL with my own
> while run `npm start` , and the end i get any message error

**Comment by Mrigank11** [comment]
Please run `npm install` again after installing new node.

**Comment by fuadhammam** [comment]
okay, it's my result

![screenshot_200](https://user-images.githubusercontent.com/22473125/36726097-25a7e336-1beb-11e8-8880-acda27d3bf9a.png)

**Comment by Mrigank11** [comment]
:man_facepalming:  This is how you declare variables:
```var CLIENT_ID = "<your id here>"```
Now change all of then this way, like:
```var CLIENT_ID="3541......content.com";```

**Comment by fuadhammam** [comment]
keep process.env ? or delete it ?

**Comment by Mrigank11** [comment]
Delete it

**Comment by fuadhammam** [comment]
was started

![screenshot_201](https://user-images.githubusercontent.com/22473125/36733069-0d42c48e-1c02-11e8-9f3a-6abf1777665d.png)

but forbidden when i check on browser

![screenshot_202](https://user-images.githubusercontent.com/22473125/36733128-3261f636-1c02-11e8-807a-862e358fa0cd.png)

**Comment by Mrigank11** [comment]
I'm sorry but without any information about your system, I don't think I can help you with this.
One thing you might wanna check is PORT.

By default, this program starts on port `3000`, which can be changed by running 
```
PORT=<some port> npm start
```
Closing for now as this is not an issue with the program itself. Feel free to comment.

**Comment by fuadhammam** [comment]
can you suggest me with similiar app ?
