### ISSUE TITLE
Error signing in GDrive

### ISSUE THREAD

**Issue by JuezFenix** [Mrigank11/embetacloud#38]
Hi, 
When i try to login, i get this:

400. That’s an error.

Error: invalid_request

Missing required parameter: redirect_uri

Learn more
Request Details

    access_type=offline
    scope=https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/drive
    response_type=code
    client_id=
    redirect_uri=

Please, fix it. Thanks

**Comment by Mrigank11** [comment]
You haven't set the required envs, see README

**Comment by abunasar** [comment]
same issue here, env are already set:

{
    "name": "eMbeta Cloud",
    "description": "Directly upload files to Cloud",
    "repository": "https://github.com/Mrigank11/embetacloud",
    "env": {
        "GOOGLE_CLIENT_ID": {
            "description": "XXXXXXXXXXXXXX.apps.googleusercontent.com"
        },
        "GOOGLE_CLIENT_SECRET": {
            "description": "XXXXXXXXXXXXXXXX"
        },
        "GOOGLE_REDIRECT_URL": {
            "description": "http://XX.185.XX.82:3000/oauthCallback"
        }
    }
}

**Comment by abunasar** [comment]
so I ditched editing app.json file and added envs directly into  /root/embetacloud/server/Storages/GDrive/GDrive.js and it works perfectly.
