### ISSUE TITLE
can't login and upload files to google drive

### ISSUE THREAD

**Issue by YogaSakti** [Mrigank11/embetacloud#40]
After adding the magnet and finished download by server, file can't be uploaded to google drive, I was already logged in but there is no indication login is this because the google app has not been verified??
![image](https://user-images.githubusercontent.com/24309806/37283849-0a049f3e-262c-11e8-9d0b-a097db997db5.png)

**Comment by Mrigank11** [comment]
The login icon (first one in top row) will turn green if you're logged in. 

How did you log in? You're supposed to click above referenced icon to login. If you clicked it, was there any error?

**Comment by YogaSakti** [comment]
hmm okay, can you send a screenshot for successful login?

**Comment by Mrigank11** [comment]
![](https://i.imgur.com/3rw8eAq.png)

**Comment by Mrigank11** [comment]
￼

**Comment by YogaSakti** [comment]
I successfully login with mega account but not with google account
