### ISSUE TITLE
please give openshift installation steps

### ISSUE THREAD

**Issue by justinechacko** [Mrigank11/embetacloud#41]
Hi, Thanks for making this app. Can you please provide openshift installation steps.

**Comment by Mrigank11** [comment]
I think Openshift supports docker images if so, it should be pretty straight-forward. Instructions for using docker image are on README. You try installing it, I'll try to help you in case something goes wrong.

PS: Sorry I can't provide you "step by step" instructions, I'm a little busy these days.

**Comment by justinechacko** [comment]
Hi, thanks for reply. I am using oc from terminal. And I logged in and created project. What is the next step

**Comment by Guilty-King** [comment]
You should check openshift docs on how to  deploy nodejs app or docker image , either should work

**Comment by Mrigank11** [comment]
torrents won't work on openshift, #29
