### ISSUE TITLE
not installing 

### ISSUE THREAD

**Issue by ghoshben** [Mrigank11/embetacloud#46]
GNU nano 2.2.6                                                 File: npm-debug.log

14 verbose headers   'cf-cache-status': 'MISS',
14 verbose headers   'cf-ray': '42bcc434be00bd5b-CDG',
14 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
14 verbose headers   vary: 'accept-encoding, accept',
14 verbose headers   server: 'cloudflare' }
15 silly registry.get cb [ 404,
15 silly registry.get   { date: 'Sat, 16 Jun 2018 10:59:21 GMT',
15 silly registry.get     'content-type': 'application/json',
15 silly registry.get     'content-length': '21',
15 silly registry.get     connection: 'keep-alive',
15 silly registry.get     'set-cookie': [ '__cfduid=d8e566c87beee2202ab8d3d00188c38ed1529146760; expires=Sun, 16-Jun-19 10:59:20 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
15 silly registry.get     'cache-control': 'max-age=300',
15 silly registry.get     'cf-cache-status': 'MISS',
15 silly registry.get     'cf-ray': '42bcc434be00bd5b-CDG',
15 silly registry.get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
15 silly registry.get     vary: 'accept-encoding, accept',
15 silly registry.get     server: 'cloudflare' } ]
16 error owner ls Couldn't get owner data upload-to-gdrive
17 error Error: Not found : upload-to-gdrive
17 error     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:300:14)
17 error     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:65)
17 error     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
17 error     at Request.emit (events.js:98:17)
17 error     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
17 error     at Request.emit (events.js:117:20)
17 error     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
17 error     at IncomingMessage.emit (events.js:117:20)
17 error     at _stream_readable.js:929:16
17 error     at process._tickCallback (node.js:419:13)
18 error If you need help, you may report this *entire* log,
18 error including the npm and node versions, at:
18 error     <http://github.com/npm/npm/issues>
19 error System Linux 3.16.0-6-amd64
20 error command "/usr/bin/nodejs" "/usr/bin/npm" "owner" "ls" "upload-to-gdrive"
21 error cwd /root/embetacloud
22 error node -v v0.10.29
23 error npm -v 1.4.21
24 verbose exit [ 1, true ]

**Comment by ghoshben** [comment]
upload-to-gdrive@1.0.0 No repository field. getting this error

**Comment by Mrigank11** [comment]
How are you trying to install this? Give full steps.
