### ISSUE TITLE
search engine add

### ISSUE THREAD

**Issue by arifbillah24** [Mrigank11/embetacloud#50]
Dear sir,

How to add 1337x search engine ?

**Comment by Mrigank11** [comment]
Currently, there's no _feature_  to add new search engines (feel free to add it :smile:  ). 

But if you just want to use 1337x instead of PiratesBay(it's down I guess?) just modify [this section](https://github.com/Mrigank11/embetacloud/blob/master/server/server.ts#L506). Feel free to ask if you need any help.

**Comment by arifbillah24** [comment]
Yes but not working .....im try.....

**Comment by arifbillah24** [comment]
if i replace 1337x.to its will be working ?

**Comment by arifbillah24** [comment]
Please Give me 1337x code and i will replace this section....

**Comment by arifbillah24** [comment]
scrapeIt(http://1337x.to/search/${encodeURIComponent(req.query.q)}/1/, {
result: {
listItem: ".box-info-detail table.table tr",
data: {
name: ".coll-1 a:nth-child(2)",
size: {
selector: ".detDesc",
convert: function (x) { return x.match(".coll-4" (.*),/)[1]; }
},
seeders: {
selector: ".coll-2",
eq: 2
},
leechers: {
selector: ".coll-3",
eq: 3
},
magnetLink: {
selector: ".download-links-dontblock a.btn","@href",
eq: 3,
attr: "href"
},
link: {
selector: ".coll-1 a:nth-child(2)",
attr: "href",
convert: function (x) { return "http://1337x.to" + x; }
}
}
}
})

**Comment by Mrigank11** [comment]
I just saw `1337x.to` and I have a bad news. Even if you fix this there's one more issue, they don't give magnet links on the search page, unlike PiratesBay. 

So, either use another search engine or you'll have to modify some more code. One possible way could be to send `magnetLink` = `1337x.to link` and add an exception for the same [here](https://github.com/Mrigank11/embetacloud/blob/master/server/server.ts#L553).

**Comment by arifbillah24** [comment]
ok. can you give me code another search engine....?

**Comment by buziyborni** [comment]
> 
> 
> I've added extratorrent, check out [extratorrent](https://github.com/Mrigank11/embetacloud/tree/extratorrent) branch.

please will this affect the thepiratebay search too or both will work

**Comment by arifbillah24** [comment]
Mrigank11 yes but 1337x best torrent search engine............

**Comment by arifbillah24** [comment]
please tell me [cloud torrent](https://github.com/jpillora/cloud-torrent) repository 1337x working is fine but your repository 1337x not working ...if i use nodejs torrent search api will be working ?
