### ISSUE TITLE
Is it possible to download files to google drive directly without downloading to our server 

### ISSUE THREAD

**Issue by arvs47** [Mrigank11/embetacloud#51]
Hi , i have this question in my mind and i searched  so much about this but there is nothing related to my queries - 

can we able to download the files directly to google drive after the auth done without downloading them to our server , i believe there are google api support url download , so is it possible to cut the server downloading and uploading process by directly uploading them from the original server ,

**Comment by Mrigank11** [comment]
I don't see how that's possible. Who will send the file to google if not the server?

**Comment by arvs47** [comment]
Yeah we need the server but  file is in external server and downloading that and  storing to our server  and again  uploading that to  gdrive is long process and a high bandwidth occurrs ,,when we initiate a download on external server we get the link right  using that link we usually download that to our server so rather than that can we sent it to gdrive  ,

**Comment by Mrigank11** [comment]
So, you want GDrive to download file from the server? (AKAIK, GDrive
doesn't provide any such feature)

Even if it did, how'll that save bandwidth? It'll still cost you the same
as uploading to drive.

**Comment by arvs47** [comment]
External server to gdrive .not downloading to our server and reupload to gdrive , there is a urlfetch in google drive API don't knoe how does it work

**Comment by Mrigank11** [comment]
> there is a urlfetch in google drive API 

Any links?

**Comment by arvs47** [comment]
https://developers.google.com/drive/api/v2/reference/files/get 
https://github.com/J05HI/google-drive-direct-remote-upload?files=1

https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app this is from app script

**Comment by Mrigank11** [comment]
>https://developers.google.com/drive/api/v2/reference/files/get 

:x: It's for getting files from GDrive, not uploading.
>https://github.com/J05HI/google-drive-direct-remote-upload?files=1

:x: He's just streaming to save space. You won't save any bandwidth.
> https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app 

:x: Irrelevant in our use case. It's for Google apps script.

Please read carefully before posting.
I'm gonna close this.

**Comment by arvs47** [comment]
Ok thanks.
Look like it is not possible yet ,because in cloud-torrent also this features are still pending ,hope some scripts will come in future ,
