### ISSUE TITLE
How to access it in google cloud vps 

### ISSUE THREAD

**Issue by arvs47** [Mrigank11/embetacloud#52]
hello i installed this in my google vps with everything is working in server side but i cannot access it in client side , 
i got the response 
 upload-to-gdrive@1.0.0 start /home/usr/embetacloud
> node server/server.js

Server Started

but when i access through the ip of my vps , i got no ip found error  even tried with port number also ,

so how can i access it in my browser do i need to configure any url in scripts or any additional configuration needed to access node js server

**Comment by Mrigank11** [comment]
> i got no ip found error 

I can't help you with just this. There are a lot of possibilities, are you using the correct ip? Is port forwarding configured correctly? etc.

Refer to the appropriate documentation for Google cloud. 

I am closing it as this is not an issue with the application.

**Comment by arvs47** [comment]
solved by adding port number in firewall rules ,

**Comment by doomwithdon** [comment]
@arvs47 , what did you specifically do in google cloud firewall settings? I am facing the same error.
