### ISSUE TITLE
Port 3000 works but 80 doesn't

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [Mrigank11/embetacloud#61]
docker run -d -p 3000:3000 -e GOOGLE_CLIENT_ID='***' -e GOOGLE_CLIENT_SECRET='***' -e GOOGLE_REDIRECT_URL='***' mrigank11/embetacloud node server/server.js

works

while

docker run -d -p 80:80 -e GOOGLE_CLIENT_ID='***' -e GOOGLE_CLIENT_SECRET='***' -e GOOGLE_REDIRECT_URL='***' mrigank11/embetacloud node server/server.js

doesn't

it worked before. like 3-4  months before.

**Comment by Mrigank11** [comment]
The command you posted should not work. See, the application runs at port `3000`(or at a port provided by the `PORT` environment variable).

So, either use `-p 80:3000`. Or add an env `PORT=80`. 

Note that the latter will require root privileges.

**Comment by ParveenBhadooOfficial** [comment]
Thanks, It worked :)
