### ISSUE TITLE
Is it possible to add authentication before they use the app.

### ISSUE THREAD

**Issue by hiiro74** [Mrigank11/embetacloud#70]
Just curious if its possible to add like a simple password authentication before they can use the app? Like check if a password is defined in an environment variable and if one is defined then prompt the user for the password before they can use the app.

**Comment by Mrigank11** [comment]
Authentication is not included in the app. However, you can easily add it yourself:
- add an `express` middleware
- set up basic authentication using a reverse proxy like Nginx or caddy.
