### ISSUE TITLE
problem with google developers project

### ISSUE THREAD

**Issue by buziyborni** [Mrigank11/embetacloud#8]
am happy you have included torrent download and it work perfectly but please can you explain more about the google developers project i try to create one i always get error when i try to link the app with the project i created on google developers. lastly i fund one bug with this project when you try to download a file and click on open and new tab will open and the file will duplicate while downloading.

**Comment by Mrigank11** [comment]
Could you please tell me what exactly is the error ?
Here are the steps:
1. You have to create a project [here](console.developers.google.com)
2. Then enable the google drive api.
3. In the credentials section create new credentials, you will get clientid and client_secret, save them as envs(as instructed in README)
There you need to authorize redirect url(s).
4. After that, setup the OAuth Consent page.

About the bug: I will fix that soon.

**Comment by buziyborni** [comment]
i did all of that i even download the credentials but i don't
 no where to place them or what to do with it. this is the error that i get when i try to login

![error 400 oauth2 error 1](https://cloud.githubusercontent.com/assets/13748342/20631057/91ce3548-b32c-11e6-9334-6f576701ba83.png)
![Uploading Error 400  OAuth2 Error   1.png…]()

**Comment by Mrigank11** [comment]
Did you set the GOOGLE_CLIENT_ID etc. envs ?
See README

**Comment by buziyborni** [comment]
yes i did but i don't no what am i really missing please can you high light on this for me please do i need to save the credentials in my root directly

**Comment by Mrigank11** [comment]
Please tell me what actually you did to save the credentials.
What you were supposed to do:
1. Get credentials from Google which I suppose you did, right?
2. Set the required environment variables, eg: on windows, `setx GOOGLE_CLIENT_ID <id>` and then start a new cmd.

Check if the environment variables are set.(on windows run: `echo %GOOGLE_CLIENT_ID%`)

**Comment by buziyborni** [comment]
this is what i did to get google credentials and i set the environment on my window laptop 
variable name to GOOGLE_CLIENT_ID,  variable Value to xxxxx.apps.googleusercontent.com
 variable name to GOOGLE_CLIENT_SECRET, Variable value to my secret code
variable name to GOOGLE_REDIRECT_URL, Variable value to http://localhost:3000/oauthCallback

![screen shot 2016-11-25 at 20 16 07](https://cloud.githubusercontent.com/assets/13748342/20634820/a5f1e496-b34c-11e6-9692-b10dc5cd296a.png)

**Comment by Mrigank11** [comment]
- How did you set the environment variables ?
If you did `set GOOGLE_CLIENT_ID=<ID>` then the variables are lost after cmd closes.
- What's the result of `echo %GOOGLE_CLIENT_ID%`
- You can get rid of this environment variable way by directly entering credentials in `server/GDrive/GDrive.js`
Then don't upload the file to Github.

**Comment by buziyborni** [comment]
i went to system property and environment variable and i set the google id there when i  echo %GOOGLE_CLIENT_ID% i still get the same result as %GOOGLE_CLIENT_ID%. please on which line should i enter the credentials in server/GDrive/GDrive.js

**Comment by Mrigank11** [comment]
This means the environment vars are not set correctly, try `setx GOOGLE_CLIENT_ID <id>`
You can edit this [line](https://github.com/Mrigank11/embetacloud/blob/master/server/GDrive/GDrive.js#L13) along with the two below it.

**Comment by buziyborni** [comment]
i edited the line and replace it with my credentials but am still getting the same error i just have to give up or please after i created the credentials do i need to do something again i just do no what exactly am doing wrong at my end

**Comment by Mrigank11** [comment]
I've added deploy to heroku button.
