### ISSUE TITLE
Folder Upload bug

### ISSUE THREAD

**Issue by vedantthete** [Mrigank11/embetacloud#9]
While uploading the entire downloaded folder to google drive, most of the times many of the files within the folder are not uploaded to drive at all.
eg: If there are 30 files in the folder and i upload it to google drive, only 15 or 20 files show up in google drive.

**Comment by Mrigank11** [comment]
Can you please specify the torrent to let me figure it out, because it is working with all torrents I tested.

**Comment by vedantthete** [comment]
https://thepiratebay.org/torrent/8175197/

**Comment by Mrigank11** [comment]
true,
I'll check, till then use the zip option.
